apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- service-monitor.yaml
secretGenerator:
- name: st-token
  files:
  - st-token.json
  type: Opaque
