apiVersion: v1
kind: Service
metadata:
  name: smartthings
  labels:
    app: smartthings
spec:
  type: ClusterIP
  selector:
    app: smartthings
  ports:
  - name: web
    protocol: TCP
    port: 9499
