prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

kubeApiServer:
  enabled: false

kubelet:
  enabled: false

kubeControllerManager:
  enabled: false

coreDns:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

kubeStateMetrics:
  enabled: false

nodeExporter:
  enabled: false
